#ifndef DEFINE_H
#define DEFINE_H


#define FONT_SIZE  16
#define MONITOR_FONT_SIZE 14

//控件之间间距
#define GRAPS_BETWEEN_CONTROLS  3
/*************************w1024*768***********************/
#define MAIN_FUNCTION_BUTTON_GRAPS 6
//window size
#define SYSTEM_WIN_WIDTH 1024
#define SYSTEM_WIN_HEIGHT 768


//用户注册窗口宽高
#define  USER_REGISYER_WIN_WIDTH 375
#define  USER_REGISYER_WIN_HEIGHT 300

//statckwidget
#define STATCKWIDGET_LEFT_MARGIN 22
#define STATCKWIDGET_BOTTOM_MARGIN 6
#define BUTTON_TO_CHOSEWIDGET_MARGIN 50

//widget 长宽设置
#define CARRIAGE_SELECT_WIDGET_HEIGHT 115
#define PLAYBACK_CARRIAGE_SELECT_WIDGET_HEIGHT 170
#define  DOWNLOAD_SET_WIDGET_WIDTH 313
//车厢状态图的widget长宽
#define  CARRIAGE_STATUS_WIDGET_WIDTH 901
#define  CARRIAGE_STATUS_WIDGET_HEIGHT 568

//button
#define CANCEL_BUTTON_WIDTH 144
#define CANCEL_BUTTON_HEIGHT 50
#define BUTTON_WIDTH  45
#define BUTTON_HEIGHT 47
#define MAIN_FUNCTION_BUTTON_WIDTH 74
#define MAIN_FUNCTION_BUTTON_HEIGHT 60
#define LOGIN_BUTTON_WIDTH 48
#define LOGIN_BUTTON_HEIGHT 14
#define LOGOUT_BUTTON_WIDTH 24
#define LOGOUT_BUTTON_HEIGHT 14
#define FILE_SEARCH_BUTTON_WIDTH 90
#define FILE_SEARCH_BUTTON_HEIGHT 30
#define FILE_DOWNLOAD_BUTTON_WIDTH 229
#define FILE_DOWNLOAD_BUTTON_HEIGHT 59
#define DEVICE_STATUS_BUTTON_WIDTH 74
#define DEVICE_STATUS_BUTTON_HEIGHT 32
//车厢状态图按钮图片宽高
#define DEVICE_ALARM_BUTTON_WIDTH 21
#define DEVICE_ALARM_BUTTON_HEIGHT 17
#define DEVICE_NVR_ALARM_BUTTON_WIDTH 11
#define DEVICE_NVR_ALARM_BUTTON_HEIGHT 11
#define DEVICE_PANTO_ALARM_BUTTON_HEIGHT 13
#define DEVICE_DRIVER_BUTTON_WIDTH  17
#define DEVICE_DRIVER_BUTTON_HEIGHT 21


//Label
#define  INIT_TIME_LABEL_WIDTH 41
#define  INIT_TIME_LABEL_HEIGHT 29
#define TIME_LABEL_WIDTH  256
#define TIME_LABEL_HEIGHT 20
//操作提示Label
#define REALMONITOR_LABEL_WIDTH 70
#define PLAYBACK_LABEL_WIDTH  120
#define LABEL_HEIGHT 40

//Edit
#define DATAEDIT_WIDTH 130
#define DATAEDIT_HEIGHT 35
#define TIMEEDIT_WIDTH 100
#define TIMEEDIT_HEIGHT 35

//slider
#define PlayBackByFileSliderHeight 20


//键盘界面
#define MMS_LOGIN_BUTTON_WIDTH				164
#define MMS_LOGIN_BUTTON_HEIGHT				50
#define MMS_LOGIN_EDIT_FRAME_WIDTH			275
#define MMS_LOGIN_EDIT_FRAME_HEIGHT			54
#define MMS_LOGIN_EDIT_WIDTH				275
#define MMS_LOGIN_EDIT_HEIGHT				30
#define MMS_LOGIN_KEYBOARD_WIDTH			710
#define MMS_LOGIN_KEYBOARD_HEIGHT			135


/*****************800*600****************************/
#define MAIN_FUNCTION_BUTTON_GRAPS_600P  3

//window size
#define SYSTEM_WIN_WIDTH_600P 800
#define SYSTEM_WIN_HEIGHT_600P 600

//statckwidget
#define STATCKWIDGET_LEFT_MARGIN_600P 10
#define STATCKWIDGET_BOTTOM_MARGIN_600P 6
#define BUTTON_TO_CHOSEWIDGET_MARGIN_600P 27

//widget 长宽设置
#define CARRIAGE_SELECT_WIDGET_HEIGHT_600P 64
#define PLAYBACK_CARRIAGE_SELECT_WIDGET_HEIGHT_600P 101
#define  DOWNLOAD_SET_WIDGET_WIDTH_600P 313
//车厢状态图的widget长宽
#define  CARRIAGE_STATUS_WIDGET_WIDTH_600P 736
#define  CARRIAGE_STATUS_WIDGET_HEIGHT_600P 460

//button
#define CANCEL_BUTTON_WIDTH_600P 137
#define CANCEL_BUTTON_HEIGHT_600P 48
#define MAIN_FUNCTION_BUTTON_WIDTH_600P 64
#define MAIN_FUNCTION_BUTTON_HEIGHT_600P 52
#define BUTTON_WIDTH_600P  33
#define BUTTON_HEIGHT_600P 34
#define LOGIN_BUTTON_WIDTH_600P 48
#define LOGIN_BUTTON_HEIGHT_600P 14
#define LOGOUT_BUTTON_WIDTH_600P 24
#define LOGOUT_BUTTON_HEIGHT_600P 14
#define FILE_SEARCH_BUTTON_WIDTH_600P 80
#define FILE_SEARCH_BUTTON_HEIGHT_600P 25
#define FILE_DOWNLOAD_BUTTON_WIDTH_600P 179
#define FILE_DOWNLOAD_BUTTON_HEIGHT_600P 47
#define DEVICE_STATUS_BUTTON_WIDTH_600P 74
#define DEVICE_STATUS_BUTTON_HEIGHT_600P 32
//车厢状态图按钮图片宽高
#define DEVICE_ALARM_BUTTON_WIDTH_600P 16
#define DEVICE_ALARM_BUTTON_HEIGHT_600P 13
#define DEVICE_NVR_ALARM_BUTTON_WIDTH_600P 9
#define DEVICE_NVR_ALARM_BUTTON_HEIGHT_600P 9
#define DEVICE_PANTO_ALARM_BUTTON_WIDTH_600P 17
#define DEVICE_PANTO_ALARM_BUTTON_HEIGHT_600P 11
#define DEVICE_DRIVER_BUTTON_WIDTH_600P  14
#define DEVICE_DRIVER_BUTTON_HEIGHT_600P 17


//label设置
#define  INIT_TIME_LABEL_WIDTH_600P 33
#define  INIT_TIME_LABEL_HEIGHT_600P 17
#define TIME_LABEL_WIDTH_600P  200
#define TIME_LABEL_HEIGHT_600P 20
//操作提示Label
#define REALMONITOR_LABEL_WIDTH_600P 70
#define PLAYBACK_LABEL_WIDTH_600P  120
#define LABEL_HEIGHT_600P 25

//Edit
#define DATAEDIT_WIDTH_600P 102
#define DATAEDIT_HEIGHT_600P 27
#define TIMEEDIT_WIDTH_600P   80
#define TIMEEDIT_HEIGHT_600P 27

//slider
#define PlayBackByFileSliderHeight_600P 20
//键盘界面
#define MMS_LOGIN_BUTTON_WIDTH_600P				136
#define MMS_LOGIN_BUTTON_HEIGHT_600P			47
#define MMS_LOGIN_EDIT_FRAME_WIDTH_600P			240
#define MMS_LOGIN_EDIT_FRAME_HEIGHT_600P		43
#define MMS_LOGIN_KEYBOARD_WIDTH_600P			552
#define MMS_LOGIN_KEYBOARD_HEIGHT_600P			134

enum CMP_OPEN_MEDIA_STATE
{
	CMP_OPEN_MEDIA_UNKOWN = 0,
	CMP_OPEN_MEDIA_FAIL,
	CMP_OPEN_MEDIA_SUCC,
	CMP_OPEN_MEDIA_LOGIN_FAIL,
	CMP_OPEN_MEDIA_STREAM_FAIL,
	CMP_OPEN_MEDIA_PLAYCONTRO_FAIL,
};

typedef struct _T_WND_INFO
{
    HWND hWnd;
    int  nX;
    int  nY;
    int  nWidth;
    int  nHeight;
    int  nVideoWidth;
    int  nVideoHeight;
    void *pRenderHandle;

}T_WND_INFO;

#endif // DEFINE_H
